var fullName = 'Ariel Donner';
var isCool = true;
var totalPets = 1;
console.log('Full Name:', fullName);
console.log('Is Cool:', isCool);
console.log('Total Pets:', totalPets);
console.log('Full Name typeof:', typeof fullName);
console.log('Is Cool typeof:', typeof isCool);
console.log('Total Pets typeof:', typeof totalPets);
var unknown = null;
console.log('Unknown:', unknown);
console.log('Unknown typeof:', typeof unknown);
var never;
console.log('Never:', never);
console.log('Never typeof:', typeof never);
